"""changed item_country to country

Revision ID: 281ffe470511
Revises: c86675ea95a1
Create Date: 2026-06-06 21:19:14.261545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281ffe470511'
down_revision = 'c86675ea95a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=2), nullable=True))
        batch_op.drop_column('item_country')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_country', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
        batch_op.drop_column('country')

    # ### end Alembic commands ###
