"""created a table for lego set data

Revision ID: 3149ad69e690
Revises: 
Create Date: 2026-05-30 05:19:59.047328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3149ad69e690'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lego_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suffix_set_num', sa.String(length=32), nullable=False),
    sa.Column('base_set_num', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('theme_id', sa.Integer(), nullable=True),
    sa.Column('num_parts', sa.Integer(), nullable=True),
    sa.Column('img_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lego_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lego_sets_base_set_num'), ['base_set_num'], unique=False)
        batch_op.create_index(batch_op.f('ix_lego_sets_suffix_set_num'), ['suffix_set_num'], unique=True)
        batch_op.create_index(batch_op.f('ix_lego_sets_theme_id'), ['theme_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lego_sets_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lego_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lego_sets_year'))
        batch_op.drop_index(batch_op.f('ix_lego_sets_theme_id'))
        batch_op.drop_index(batch_op.f('ix_lego_sets_suffix_set_num'))
        batch_op.drop_index(batch_op.f('ix_lego_sets_base_set_num'))

    op.drop_table('lego_sets')
    op.drop_table('themes')
    # ### end Alembic commands ###
