"""changed set_num to string

Revision ID: 2b7122d939b7
Revises: 
Create Date: 2026-06-07 15:49:48.105291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b7122d939b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.alter_column('set_num',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_listings_set_num'), ['set_num'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_set_num'))
        batch_op.alter_column('set_num',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
