"""initial schema

Revision ID: 6ac2dc32c8ef
Revises: 
Create Date: 2026-06-11 08:36:59.439616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac2dc32c8ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ebay_item_id', sa.String(), nullable=False),
    sa.Column('set_num', sa.String(length=32), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('image_urls', sa.JSON(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('marketplace', sa.String(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('status', sa.String(), server_default='ACTIVE', nullable=True),
    sa.Column('affiliate_url', sa.Text(), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ebay_item_id')
    )
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listings_set_num'), ['set_num'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_status'), ['status'], unique=False)

    op.create_table('temp_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ebay_item_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('buying_options', sa.JSON(), nullable=True),
    sa.Column('image_urls', sa.JSON(), nullable=True),
    sa.Column('item_url', sa.Text(), nullable=True),
    sa.Column('affiliate_url', sa.Text(), nullable=True),
    sa.Column('seller_username', sa.String(length=100), nullable=True),
    sa.Column('seller_feedback_score', sa.Integer(), nullable=True),
    sa.Column('seller_feedback_percent', sa.Float(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('marketplace', sa.String(), nullable=True),
    sa.Column('item_country', sa.String(length=2), nullable=True),
    sa.Column('item_city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('item_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ebay_item_id')
    )
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lego_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suffix_set_num', sa.String(length=32), nullable=False),
    sa.Column('base_set_num', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('theme_id', sa.Integer(), nullable=True),
    sa.Column('num_parts', sa.Integer(), nullable=True),
    sa.Column('img_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lego_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lego_sets_base_set_num'), ['base_set_num'], unique=False)
        batch_op.create_index(batch_op.f('ix_lego_sets_suffix_set_num'), ['suffix_set_num'], unique=True)
        batch_op.create_index(batch_op.f('ix_lego_sets_theme_id'), ['theme_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lego_sets_year'), ['year'], unique=False)

    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_history_recorded_at'), ['recorded_at'], unique=False)

    op.create_table('set_price_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.Column('marketplace', sa.String(length=10), nullable=True),
    sa.Column('listing_count', sa.Integer(), nullable=True),
    sa.Column('min_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('avg_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('median_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['lego_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('set_price_stats')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_recorded_at'))

    op.drop_table('price_history')
    with op.batch_alter_table('lego_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lego_sets_year'))
        batch_op.drop_index(batch_op.f('ix_lego_sets_theme_id'))
        batch_op.drop_index(batch_op.f('ix_lego_sets_suffix_set_num'))
        batch_op.drop_index(batch_op.f('ix_lego_sets_base_set_num'))

    op.drop_table('lego_sets')
    op.drop_table('themes')
    op.drop_table('temp_summaries')
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_status'))
        batch_op.drop_index(batch_op.f('ix_listings_set_num'))

    op.drop_table('listings')
    # ### end Alembic commands ###
