"""fresh

Revision ID: 6f8ebe30ccf7
Revises: 
Create Date: 2026-04-30 00:50:38.489768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f8ebe30ccf7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ebay_item_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('buying_options', sa.JSON(), nullable=True),
    sa.Column('image_urls', sa.JSON(), nullable=True),
    sa.Column('item_url', sa.Text(), nullable=True),
    sa.Column('affiliate_url', sa.Text(), nullable=True),
    sa.Column('seller_username', sa.String(length=100), nullable=True),
    sa.Column('seller_feedback_score', sa.Integer(), nullable=True),
    sa.Column('seller_feedback_percent', sa.Float(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('item_country', sa.String(length=2), nullable=True),
    sa.Column('item_city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('item_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ebay_item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp_summaries')
    # ### end Alembic commands ###
