"""updated listings

Revision ID: 7cd68bf593ef
Revises: 950d2bf42293
Create Date: 2026-05-17 22:42:06.207060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd68bf593ef'
down_revision = '950d2bf42293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_urls', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('condition', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('condition')
        batch_op.drop_column('image_urls')

    # ### end Alembic commands ###
