"""added marketplace column

Revision ID: 950d2bf42293
Revises: f489085e4499
Create Date: 2026-05-12 01:49:37.785553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950d2bf42293'
down_revision = 'f489085e4499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temp_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marketplace', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temp_summaries', schema=None) as batch_op:
        batch_op.drop_column('marketplace')

    # ### end Alembic commands ###
