"""added miss_count and ended_at

Revision ID: bff168d1f9db
Revises: 2b7122d939b7
Create Date: 2026-06-14 17:53:22.011299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff168d1f9db'
down_revision = '2b7122d939b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('miss_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ended_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('ended_at')
        batch_op.drop_column('miss_count')

    # ### end Alembic commands ###
