"""added setpricestats table

Revision ID: c86675ea95a1
Revises: 3149ad69e690
Create Date: 2026-06-04 03:24:18.789150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c86675ea95a1'
down_revision = '3149ad69e690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('set_price_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.Column('marketplace', sa.String(length=10), nullable=True),
    sa.Column('listing_count', sa.Integer(), nullable=True),
    sa.Column('min_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('avg_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('median_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['lego_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('set_price_stats')
    # ### end Alembic commands ###
