"""add listing + pricehistory indexes

Revision ID: ea6f9c577e73
Revises: 8859a899f522
Create Date: 2026-06-15 23:03:07.319920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea6f9c577e73'
down_revision = '8859a899f522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index('ix_listings_active_marketplace_setnum', ['status', 'marketplace', 'set_num'], unique=False)

    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index('ix_pricehistory_listing_time', ['listing_id', 'recorded_at', 'id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index('ix_pricehistory_listing_time')

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index('ix_listings_active_marketplace_setnum')

    # ### end Alembic commands ###
