"""added listings

Revision ID: f489085e4499
Revises: bde18e7e1a7c
Create Date: 2026-05-11 00:36:16.717810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f489085e4499'
down_revision = 'bde18e7e1a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marketplace', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), server_default='ACTIVE', nullable=True))
        batch_op.create_index(batch_op.f('ix_listings_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_status'))
        batch_op.drop_column('status')
        batch_op.drop_column('marketplace')

    # ### end Alembic commands ###
